name: paycare cyril TP github actions

on: 
  push:
    branches: ["main","dev"]
  workflow_dispatch:
    
jobs:
  # Test API Job 
  etl1:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install pytest
        run: pip install pytest pytest-mock

      - name: run tests
        env: 
          PYTHONPATH: ${{github.workspace}}  
        run: pytest tests


      - name: docker build image
        run: docker build -t paycare_cyril .

      - name: docker run
        run: docker run --rm -v $(pwd)/data:/home/data paycare_cyril

      - name: docker status
        run: docker ps

      - name: upload_atifact
        uses: actions/upload-artifact@v4   # ✅ uses, et nom singulier "artifact"
        with:
          name: my-artifact
          path: data/output_data.csv
